import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <body style={{backgroundColor:"black",justifyItems:"center",alignItems:"center", color:"white"}}
      >
        {children}
      </body>
    </html>
  );
}
